- name: Configure DNS Resolvers
  hosts: all
  tasks:
    - name: Update resolv.conf
      ansible.builtin.copy:
        dest: /etc/resolv.conf
        content: |
          nameserver 8.8.8.8
          nameserver 1.1.1.1
          search mydomain.com
